<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="color.xacro" />
    <xacro:include filename="robot_dimensions.xacro" />

    <!-- BASE LINK -->
    <link name="base_link">
    
    </link>

    <!--CHASSIS LINK-->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-0.1 0 0"/>
    </joint>

    <link name="chassis_link">
        <visual>
            <origin xyz="${body_radius / 2.0} 0 ${body_length/2}"/>
            <geometry>
                <cylinder radius="${body_diameter / 2.0}" length="${body_length}"/>
            </geometry>
            <material name="white"/>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="${body_diameter / 2.0}" length="${body_length}"/>
        </geometry>
    </collision>
    <inertial>
        <mass value="1.0"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="-0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    </link>

</robot>