<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Body dimensions (in meters) -->
  <!-- Body is a cylinder: diameter = 120mm (0.12 m), length = 80mm (0.08 m) -->
  <xacro:property name="body_diameter" value="0.12"/>
  <xacro:property name="body_length" value="0.08"/>
  <xacro:property name="body_radius" value="${body_diameter / 2.0}"/>

  <!-- Wheel dimensions -->
  <!-- Wheel diameter = 60mm (0.06 m); radius is half of that -->
  <xacro:property name="wheel_diameter" value="0.06"/>
  <xacro:property name="wheel_radius" value="${wheel_diameter / 2.0}"/>
  <!-- Distance between the centers of the left and right wheels = 150mm (0.15 m) -->
  <xacro:property name="wheel_separation" value="0.15"/>
  <xacro:property name="wheel_mass" value="0.05"/>
  <xacro:property name="wheel_thickness" value="0.026"/>
  <xacro:property name="wheel_offset_x" value="0.226"/>
  <xacro:property name="wheel_offset_y" value="0.1485"/>
  <xacro:property name="wheel_offset_z" value="0.01"/>

  <!-- Lidar dimensions -->
  <!-- Represent the lidar as a cylinder with diameter = 70mm (0.07 m) -->
  <xacro:property name="lidar_diameter" value="0.07"/>
  <!-- Arbitrarily set a height for the lidar cylinder, e.g. 20mm (0.02 m) -->
  <xacro:property name="lidar_height" value="0.02"/>
  <!-- The lidar is mounted on the top of the body but offset by 30mm (0.03 m) down from the top -->
  <xacro:property name="lidar_offset_from_top" value="0.03"/>

  <!-- Caster wheel dimensions -->
  <xacro:property name="caster_distance" value="0.03"/>
  <!-- caster_wheel_radius changed to caster_radius-->
  <xacro:property name="caster_radius" value="0.015"/>
  <xacro:property name="caster_wheel_mass" value="0.01"/>
  <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_radius}"/>
</robot>
